# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the tag.
        options:
        - "@order"
        - "@positive"
        - "@negative"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Remove node.js
      run: sudo apt-get purge nodejs
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install Google Chrome 
      run: |
        sudo chmod +x ./scripts/installChrome.sh
        sudo ./scripts/installChrome.sh
    - name: Build with Maven
      run: mvn test -Dcucumber.filter.tags="${{ github.event.inputs.choice }}"
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      #if: failure()
      with:
        name: screenshot
        path: /home/runner/work/paymentFlowValidation/paymentFlowValidation/screenshot
